INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (1,11,"RONDONIA","RO");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (2,12,"ACRE","AC");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (3,13,"AMAZONAS","AM");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (4,14,"RORAIMA","RR");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (5,15,"PARA","PA");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (6,16,"AMAPA","AP");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (7,17,"TOCANTINS","TO");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (8,21,"MARANHAO","MA");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (9,22,"PIAUI","PI");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (10,23,"CEARA","CE");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (11,24,"RIO GRANDE DO NORTE","RN");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (12,25,"PARAIBA","PB");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (13,26,"PENAMBUCO","PE");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (14,27,"ALAGOAS","AL");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (15,28,"SERGIPE","SE");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (16,29,"BAHIA","BA");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (17,31,"MINAS GERAIS","MG");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (18,32,"ESPIRITO SANTO","ES");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (19,33,"RIO DE JANEIRO","RJ");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (20,35,"SAO PAULO","SP");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (21,41,"PARANA","PR");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (22,42,"SANTA CATARINA","SC");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (23,43,"RIO GRANDE DO SUL","RS");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (24,50,"MATO GROSSO DO SUL","MS");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (25,51,"MATO GROSSO","MT");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (26,52,"GOIAS","GO");
INSERT INTO ESTADO (id,codigo_uf,nome,uf) values (27,53,"DISTRITO FEDERAL","DF");
